fintest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import navserver.urls

urlpatterns = [
    url(r'^navserver/', include(navserver.urls)),
    url(r'^admin/', admin.site.urls),
]

navserver/urls.py
from django.conf.urls import url

from . import views

app_name = 'navserver'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<amfisymbol>[0-9]{6})/(?P<startdate>[0-9]{8})-(?P<enddate>[0-9]{8}).json$', views.navjson, name='navjson'),
    url(r'^(?P<amfisymbol1>[0-9]{6}),(?P<amfisymbol2>[0-9]{6})/(?P<startdate>[0-9]{8})-(?P<enddate>[0-9]{8}).json$', views.lumpsumcompare, name='lumpsumcompare'),
    url(r'^(?P<amfisymbol1>[0-9]{6}),(?P<amfisymbol2>[0-9]{6})/(?P<startdate>[0-9]{8})-(?P<enddate>[0-9]{8})/$', views.lumpsumview, name='lumpsumview'),
    url(r'^(?P<amfisymbol>[0-9]{6})/(?P<startdate>[0-9]{8})-(?P<enddate>[0-9]{8})/$', views.navview, name='navview'),
]

navserver/models.py
from django.db import models

class MutualFund(models.Model):
    amfisymbol = models.CharField(max_length=10, unique=True)
    mfname = models.CharField(max_length=300,default='Unnamed MF')

    def __str__(self):
        return self.amfisymbol

class MutualFundNAV(models.Model):
    mf = models.ForeignKey(MutualFund, related_name="nav", on_delete=models.CASCADE)
    date = models.DateField(db_index=True)
    nav = models.DecimalField(max_digits=20,decimal_places=6)

    def __str__(self):
        return "%s, %s, %s" % (self.mf.amfisymbol, str(self.date), str(self.nav))

navserver/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, JsonResponse
from django.template import loader

from .models import MutualFund, MutualFundNAV

def index(request):
    mflist = MutualFund.objects.order_by('-mfname')
    template = loader.get_template('navserver/index.html')
    context = {
        'mflist': mflist,
        'startdate': '20150814',
        'enddate': '20160814',
    }
    return HttpResponse(template.render(context, request))

def navlist(amfisymbol, startdate, enddate):
    try:
        mf = MutualFund.objects.get(amfisymbol=amfisymbol)
    except:
        raise Http404("MF does not exist!")

    hyphenate_date = lambda x : x[:4] + '-' + x[4:6] + '-' + x[6:]
    startdate = hyphenate_date(startdate)
    enddate = hyphenate_date(enddate)
    nav_values = mf.nav.filter(date__range = (startdate, enddate)).order_by('date')
    return list(nav_values.values('date', 'nav'))

def navjson(request, amfisymbol, startdate, enddate):
    return JsonResponse(navlist(amfisymbol, startdate, enddate), safe=False)

def lumpsumcompare(request, amfisymbol1, amfisymbol2, startdate, enddate):
    nav_list_1 = navlist(amfisymbol1, startdate, enddate)
    nav_list_1_multiple = 10000.0 / float(nav_list_1[0]['nav'])
    print(nav_list_1[0]['nav'])
    print(nav_list_1_multiple)
    nav_list_1 = [{"date" : i['date'],
                       'value' : '{:.2f}'.format(nav_list_1_multiple * float(i['nav']))}
                       for i in nav_list_1]
    nav_list_2 = navlist(amfisymbol2, startdate, enddate)
    nav_list_2_multiple = 10000.0 / float(nav_list_2[0]['nav'])
    print(nav_list_2[0]['nav'])
    print(nav_list_2_multiple)
    print(nav_list_2_multiple * float(nav_list_2[0]['nav']))
    nav_list_2 = [{"date" : i['date'],
                       'value' : '{:.2f}'.format(nav_list_2_multiple * float(i['nav']))}
                       for i in nav_list_2]
    return JsonResponse([nav_list_1, nav_list_2], safe=False)

def navview(request, amfisymbol, startdate, enddate):
    try:
        mf = MutualFund.objects.get(amfisymbol=amfisymbol)
    except:
        raise Http404("MF does not exist!")
    template = loader.get_template('navserver/navview.html')
    context = {
        'amfisymbol' : amfisymbol,
        'mfname' : mf.mfname,
        'startdate' : startdate,
        'enddate' : enddate,}
    return HttpResponse(template.render(context, request))

def lumpsumview(request, amfisymbol1, amfisymbol2, startdate, enddate):
    try:
        mf1 = MutualFund.objects.get(amfisymbol=amfisymbol1)
        mf2 = MutualFund.objects.get(amfisymbol=amfisymbol2)
    except:
        raise Http404("MF does not exist!")
    template = loader.get_template('navserver/navcompare.html')
    context = {
        'amfisymbol1' : amfisymbol1,
        'mfname1' : mf1.mfname,
        'amfisymbol2' : amfisymbol2,
        'mfname2' : mf2.mfname,
        'startdate' : startdate,
        'enddate' : enddate,}
    return HttpResponse(template.render(context, request))
    

navserver/templates/navserver/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        @import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);

        body {
            font-family: 'Source Sans Pro';
        }

        html {
            font-size: 1em;
        }
    </style>
    <title>NAV analyzer</title>
</head>
<body>
  <h1>NAV analyzer</h1>
{% if mflist %}
  <p>We currently track the following mutual funds:</p>
  <ul>
    {% for mf in mflist %}
    <li><a href="{% url 'navserver:navview' mf.amfisymbol startdate enddate %}">{{ mf.mfname }}</a></li>
    {% endfor %}
  </ul>
{% endif %}
</body>
</html>

navserver/templates/navserver/navcompare.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://d3js.org/d3.v4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.10.1/metricsgraphics.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.10.1/metricsgraphics.css"
    rel="stylesheet" type="text/css"/>
    <style>
        @import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);

        body {
            font-family: 'Source Sans Pro';
        }

        html {
            font-size: 1em;
        }
    </style>
    <title></title>
</head>
<body>
  <h1>Growth of Rs. 10,000 in {{ mfname1 }} and {{ mfname2 }}</h1>
  <div id="chart"></div>
   <script>
     makechart = function(charturl, chartid) {
     d3.json(charturl, function(data) {
     for (var i = 0; i < data.length; i++) {
         data[i] = MG.convert.date(data[i], 'date');
         data[i] = MG.convert.number(data[i], 'value');
     }
         MG.data_graphic({
             title: "Performance of {{ mfname1 }}, {{ mfname2 }} ",
             description: "NAV of {{ mfname }}",
             data: data,
             width: 600,
             height: 375,
             right: 40,
	     legend: ['{{ mfname1 }}', '{{ mfname2 }}'],
             legend_target: 'div#mylegend',
             target: "#" + chartid,
             x_accessor: "date",
             y_accessor: "value",
	     area: false,
	     transition_on_update: false,
         });
     });
     };
     makechart('{% url 'navserver:lumpsumcompare' amfisymbol1 amfisymbol2 startdate enddate %}', "chart");
    </script>
   <div id="mylegend"></div>
    <h3>Past returns</h3>
    <ul>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol1 }},{{ amfisymbol2 }}/20150814-20160814.json', 'chart')">1 year</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol1 }},{{ amfisymbol2 }}/20140814-20160814.json', 'chart')">2 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol1 }},{{ amfisymbol2 }}/20130814-20160814.json', 'chart')">3 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol1 }},{{ amfisymbol2 }}/20120814-20160814.json', 'chart')">4 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol1 }},{{ amfisymbol2 }}/20110814-20160814.json', 'chart')">5 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol1 }},{{ amfisymbol2 }}/20100814-20160814.json', 'chart')">6 years</a></li>
    </ul>
</body>
</html>

navserver/templates/navserver/navview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://d3js.org/d3.v4.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.10.1/metricsgraphics.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/metrics-graphics/2.10.1/metricsgraphics.css"
    rel="stylesheet" type="text/css"/>
    <style>
        @import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro);

        body {
            font-family: 'Source Sans Pro';
        }

        html {
            font-size: 1em;
        }
    </style>
    <title>Performance of {{ mfname }}</title>
</head>
<body>
  <h1>Performance of {{ mfname }}</h1>
  <div id="chart"></div>
   <script>
     makechart = function(charturl, chartid) {
     d3.json(charturl, function(data) {
         data = MG.convert.date(data, 'date');
         data = MG.convert.number(data, 'nav');
         MG.data_graphic({
             title: "Performance of {{ mfname }} ",
             description: "NAV of {{ mfname }}",
             data: data,
             width: 600,
             height: 375,
             target: "#" + chartid,
             x_accessor: "date",
             y_accessor: "nav",
	     area: true,
	     transition_on_update: false,
         });
     });
     };
     makechart('{% url 'navserver:navjson' amfisymbol startdate enddate %}', "chart");
    </script>
    <h3>Past returns</h3>
    <ul>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol }}/20150814-20160814.json', 'chart')">1 year</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol }}/20140814-20160814.json', 'chart')">2 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol }}/20130814-20160814.json', 'chart')">3 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol }}/20120814-20160814.json', 'chart')">4 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol }}/20110814-20160814.json', 'chart')">5 years</a></li>
	<li><a href="javascript:makechart('/navserver/{{ amfisymbol }}/20100814-20160814.json', 'chart')">6 years</a></li>
    </ul>
</body>
</html>